[deps]
BioSequences = "7e6ae17a-c86d-528c-b3b9-7f778a29fe59"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FASTX = "c2308a5c-f048-11e8-3e8a-31650f418d12"
Kmers = "445028e4-d31f-4f27-89ad-17affd83fc22"
MinHash = "4b3c9753-2685-44e9-8a29-365b96c023ed"

[sources]
Kmers = {path = ".."}

[compat]
Documenter = "1"
